import{a as m,S as y,i as a}from"./assets/vendor-CYg6pwNI.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function s(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=s(r);fetch(r.href,o)}})();const g="49170248-1681c7614cb0540d906e8c034",b="https://pixabay.com/api/";async function f(e,t=1,s=15){try{return(await m.get(b,{params:{key:g,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,perPage:s}})).data}catch(n){throw console.error("Ошибка при завантаженнi зображення",n),n}}const p=document.querySelector(".gallery"),L=document.querySelector("#load-more");let w=new y(".gallery a",{captionData:"alt",captionDelay:250});function v(e){return e.map(t=>`
                <li class="gallery-item">
            <a href="${t.largeImageURL}">
                <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy"/>
            </a>
            <div class="info">
                <p><b>Likes:</b> ${t.likes}</p>
                <p><b>Views:</b> ${t.views}</p>
                <p><b>Comments:</b> ${t.comments}</p>
                <p><b>Downloads:</b> ${t.downloads}</p>
            </div>
        </li>`).join("")}function h(e){if(!e||e.length===0){a.warning({title:"Oops",message:"No images found",position:"topRight"});return}p.insertAdjacentHTML("beforeend",v(e)),w.refresh()}function E(){p.innerHTML=""}function u(e){L.style.display=e?"block":"none"}function S(){const{height:e}=p.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}const R=document.querySelector(".form"),q=document.querySelector("#search-input"),$=document.querySelector("#load-more");let i=1,c="",d=0;R.addEventListener("submit",async e=>{if(e.preventDefault(),c=q.value.trim(),!c){a.error({title:"Error",message:"Enter a search query",position:"topRight"});return}E(),i=1,u(!1);try{const{hits:t,totalHits:s}=await f(c,i);d=s,h(t),t.length<d&&u(!0)}catch{a.error({title:"Error",message:"Failed to fetch images. Try again.",position:"topRight"})}});$.addEventListener("click",async()=>{i++;try{const{hits:e}=await f(c,i);h(e),S(),i*15>=d&&(u(!1),a.info({title:"End",message:"We're sorry, but you've reached the end of search results",position:"topRight"}))}catch{a.error({title:"Error",message:"Failed to fetch more images.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
